
services:
  backend:
    depends_on:
      - db-postgres
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: base
    volumes:
      - ./backend/src:/usr/smsArchiver/backend/src
      - ./backend/prisma:/usr/smsArchiver/backend/prisma
      - ./backend/node_modules/.prisma/client:/usr/smsArchiver/backend/node_modules/.prisma/client
      - backend-modules:/usr/smsArchiver/backend/node_modules
    environment:
      NODE_ENV: development
    ports:
      - 8000:8000
    command: npm run dev
      
  pgadmin:
    depends_on:
      - db-postgres
    image: dpage/pgadmin4
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  db-postgres:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
  pgadmin-data:
  backend-modules:
